name: Build Lambda ZIP

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -t lambda-builder .

    - name: Extract Lambda package
      run: |
        docker create --name temp lambda-builder
        docker cp temp:/build/lambda_package.zip .
        docker rm temp

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: lambda-package
        path: lambda_package.zip
